### PR TITLE
LPS-75962 OSGi implementation of Analytics Client + Use Petra Client

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by epgarcia** [comment]
Hi @marcellustavares 

These are the changes to provide an Analytics Client as an OSGi service in Liferay. Basically I:

- Created a module analytics-client-osgi (following the same pattern as in https://github.com/liferay/com-liferay-lcs-private, see messagin-osgi)
- Added a service that implements AnalyticsClient and depends on the petra JSONWebServiceClient and the JSONObjectMapper as provided (i.e. they should all be available in Liferay).
- Created an integration test to validate that the service is resolved and works. I marked is as Ignored because the gateway being down would break CI; I still have to find an alternative for this. But feel free to remove the annotation and run gradlew testIntegration.
- You should use the latest version of the JVM, otherwise you would get a security error. (I'm using 1.8.0_151).
- Additionally, I renamed the java-client to simply client-impl (I think the java is redundant here, we should only use suffix for special cases like -js, -osgi, -swift...) and for consistency I applied the petra JSONWebServiceClient  here too, but standalone (it's a compileInclude). As you see, because the SF fails when importing classes from internal packages (as the implementations of the JSONWebServiceClient and  JSONObjectMapper) I had to include this client from the SF. I will ask Hugo about this particular case later.

Please feel free to add any changes you find necessary and to ask me in case of doubt. :)

**Comment by epgarcia** [comment]
ci:retest

**Comment by epgarcia** [comment]
@juliocamarero

**Comment by epgarcia** [comment]
Forwarded to the Liferay user. See: https://github.com/liferay/com-liferay-analytics/pull/24

**Comment by marcellustavares** [comment]
thanks @epgarcia, we'll apply the changes locally to the apps and let you know if everything is ok.

**Pull request closed without merging**
